name: anki-pinyin
dependencies:
 - python=3.9.15
 - pip
 - pip:
    #  - -i https://pypi.tuna.tsinghua.edu.cn/simple
     - mypy
     - PyYAML
     - aqt[qt6]
     # chinese
     - jieba
     - pypinyin
     - pycantonese
     - opencc-python-reimplemented 